name: Update submodule

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Update submodule
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git submodule update --remote --recursive

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update linutil submodule
          file_pattern: "linutil/**"
